#!/bin/sh

DISTDIR=pyxbdist
cd /tmp
rm -rf ${DISTDIR}
svn checkout svn://scmhome/pyxb/trunk ${DISTDIR}
cd ${DISTDIR}
cd doc
rm -rf html
rm -f pyxb
ln -s ../pyxb .
make apihtml
make  html
rm -f pyxb
cd ..
maintainer/dobinds.sh
maintainer/wssplat.sh
./setup.py sdist
./setup.py test
cp -p dist/PyXB-*.tar.gz ~/pyxb/pre-release
