"""Material used to generate and execute bindings generated by the PyXB package.
"""

# Automatically include all the stuff that's necessary for basic
# running.  There are order dependencies here.
import basis
import datatypes
import facets
import datatypes_facets
import content

# Do not include the stuff that's required only for code generation
# noimport nfa
# noimport generate
