import facets
from datatypes import *
ENTITIES._CF_minLength = facets.CF_minLength(value=nonNegativeInteger(1))
ENTITIES._InitializeFacetMap(ENTITIES._CF_minLength)
gYearMonth._CF_whiteSpace = facets.CF_whiteSpace(value=facets._WhiteSpace_enum.collapse)
gYearMonth._InitializeFacetMap(gYearMonth._CF_whiteSpace)
NMTOKENS._CF_minLength = facets.CF_minLength(value=nonNegativeInteger(1))
NMTOKENS._InitializeFacetMap(NMTOKENS._CF_minLength)
date._CF_whiteSpace = facets.CF_whiteSpace(value=facets._WhiteSpace_enum.collapse)
date._InitializeFacetMap(date._CF_whiteSpace)
time._CF_whiteSpace = facets.CF_whiteSpace(value=facets._WhiteSpace_enum.collapse)
time._InitializeFacetMap(time._CF_whiteSpace)
gYear._CF_whiteSpace = facets.CF_whiteSpace(value=facets._WhiteSpace_enum.collapse)
gYear._InitializeFacetMap(gYear._CF_whiteSpace)
dateTime._CF_whiteSpace = facets.CF_whiteSpace(value=facets._WhiteSpace_enum.collapse)
dateTime._InitializeFacetMap(dateTime._CF_whiteSpace)
duration._CF_whiteSpace = facets.CF_whiteSpace(value=facets._WhiteSpace_enum.collapse)
duration._InitializeFacetMap(duration._CF_whiteSpace)
decimal._CF_whiteSpace = facets.CF_whiteSpace(value=facets._WhiteSpace_enum.collapse)
decimal._InitializeFacetMap(decimal._CF_whiteSpace)
double._CF_whiteSpace = facets.CF_whiteSpace(value=facets._WhiteSpace_enum.collapse)
double._InitializeFacetMap(double._CF_whiteSpace)
boolean._CF_whiteSpace = facets.CF_whiteSpace(value=facets._WhiteSpace_enum.collapse)
boolean._InitializeFacetMap(boolean._CF_whiteSpace)
float._CF_whiteSpace = facets.CF_whiteSpace(value=facets._WhiteSpace_enum.collapse)
float._InitializeFacetMap(float._CF_whiteSpace)
string._CF_whiteSpace = facets.CF_whiteSpace(value=facets._WhiteSpace_enum.preserve)
string._InitializeFacetMap(string._CF_whiteSpace)
IDREFS._CF_minLength = facets.CF_minLength(value=nonNegativeInteger(1))
IDREFS._InitializeFacetMap(IDREFS._CF_minLength)
NOTATION._CF_whiteSpace = facets.CF_whiteSpace(value=facets._WhiteSpace_enum.collapse)
NOTATION._InitializeFacetMap(NOTATION._CF_whiteSpace)
QName._CF_whiteSpace = facets.CF_whiteSpace(value=facets._WhiteSpace_enum.collapse)
QName._InitializeFacetMap(QName._CF_whiteSpace)
anyURI._CF_whiteSpace = facets.CF_whiteSpace(value=facets._WhiteSpace_enum.collapse)
anyURI._InitializeFacetMap(anyURI._CF_whiteSpace)
base64Binary._CF_whiteSpace = facets.CF_whiteSpace(value=facets._WhiteSpace_enum.collapse)
base64Binary._InitializeFacetMap(base64Binary._CF_whiteSpace)
hexBinary._CF_whiteSpace = facets.CF_whiteSpace(value=facets._WhiteSpace_enum.collapse)
hexBinary._InitializeFacetMap(hexBinary._CF_whiteSpace)
gMonth._CF_whiteSpace = facets.CF_whiteSpace(value=facets._WhiteSpace_enum.collapse)
gMonth._InitializeFacetMap(gMonth._CF_whiteSpace)
gDay._CF_whiteSpace = facets.CF_whiteSpace(value=facets._WhiteSpace_enum.collapse)
gDay._InitializeFacetMap(gDay._CF_whiteSpace)
integer._CF_fractionDigits = facets.CF_fractionDigits(value=nonNegativeInteger(0))
integer._CF_pattern = facets.CF_pattern()
integer._CF_pattern.addPattern(pattern=u'[\\-+]?[0-9]+')
integer._InitializeFacetMap(integer._CF_fractionDigits,
   integer._CF_pattern)
gMonthDay._CF_whiteSpace = facets.CF_whiteSpace(value=facets._WhiteSpace_enum.collapse)
gMonthDay._InitializeFacetMap(gMonthDay._CF_whiteSpace)
normalizedString._CF_whiteSpace = facets.CF_whiteSpace(super_facet=string._CF_whiteSpace, value=facets._WhiteSpace_enum.replace)
normalizedString._InitializeFacetMap(normalizedString._CF_whiteSpace)
nonNegativeInteger._CF_minInclusive = facets.CF_minInclusive(value_datatype=nonNegativeInteger, value=nonNegativeInteger(0))
nonNegativeInteger._InitializeFacetMap(nonNegativeInteger._CF_minInclusive)
long._CF_maxInclusive = facets.CF_maxInclusive(value_datatype=long, value=long(9223372036854775807))
long._CF_minInclusive = facets.CF_minInclusive(value_datatype=long, value=long(-9223372036854775808))
long._InitializeFacetMap(long._CF_maxInclusive,
   long._CF_minInclusive)
nonPositiveInteger._CF_maxInclusive = facets.CF_maxInclusive(value_datatype=nonPositiveInteger, value=nonPositiveInteger(0))
nonPositiveInteger._InitializeFacetMap(nonPositiveInteger._CF_maxInclusive)
positiveInteger._CF_minInclusive = facets.CF_minInclusive(value_datatype=positiveInteger, super_facet=nonNegativeInteger._CF_minInclusive, value=positiveInteger(1))
positiveInteger._InitializeFacetMap(positiveInteger._CF_minInclusive)
token._CF_whiteSpace = facets.CF_whiteSpace(super_facet=normalizedString._CF_whiteSpace, value=facets._WhiteSpace_enum.collapse)
token._InitializeFacetMap(token._CF_whiteSpace)
unsignedLong._CF_maxInclusive = facets.CF_maxInclusive(value_datatype=unsignedLong, value=unsignedLong(18446744073709551615))
unsignedLong._InitializeFacetMap(unsignedLong._CF_maxInclusive)
Name._CF_pattern = facets.CF_pattern()
Name._CF_pattern.addPattern(pattern=u'\\i\\c*')
Name._InitializeFacetMap(Name._CF_pattern)
int._CF_maxInclusive = facets.CF_maxInclusive(value_datatype=int, super_facet=long._CF_maxInclusive, value=int(2147483647))
int._CF_minInclusive = facets.CF_minInclusive(value_datatype=int, super_facet=long._CF_minInclusive, value=int(-2147483648))
int._InitializeFacetMap(int._CF_maxInclusive,
   int._CF_minInclusive)
negativeInteger._CF_maxInclusive = facets.CF_maxInclusive(value_datatype=negativeInteger, super_facet=nonPositiveInteger._CF_maxInclusive, value=negativeInteger(-1))
negativeInteger._InitializeFacetMap(negativeInteger._CF_maxInclusive)
NCName._CF_pattern = facets.CF_pattern(super_facet=Name._CF_pattern)
NCName._CF_pattern.addPattern(pattern=u'[\\i-[:]][\\c-[:]]*')
NCName._InitializeFacetMap(NCName._CF_pattern)
ID._InitializeFacetMap()
NMTOKEN._CF_pattern = facets.CF_pattern()
NMTOKEN._CF_pattern.addPattern(pattern=u'\\c+')
NMTOKEN._InitializeFacetMap(NMTOKEN._CF_pattern)
language._CF_pattern = facets.CF_pattern()
language._CF_pattern.addPattern(pattern=u'[a-zA-Z]{1,8}(-[a-zA-Z0-9]{1,8})*')
language._InitializeFacetMap(language._CF_pattern)
unsignedInt._CF_maxInclusive = facets.CF_maxInclusive(value_datatype=unsignedInt, super_facet=unsignedLong._CF_maxInclusive, value=unsignedInt(4294967295))
unsignedInt._InitializeFacetMap(unsignedInt._CF_maxInclusive)
short._CF_maxInclusive = facets.CF_maxInclusive(value_datatype=short, super_facet=int._CF_maxInclusive, value=short(32767))
short._CF_minInclusive = facets.CF_minInclusive(value_datatype=short, super_facet=int._CF_minInclusive, value=short(-32768))
short._InitializeFacetMap(short._CF_maxInclusive,
   short._CF_minInclusive)
IDREF._InitializeFacetMap()
ENTITY._InitializeFacetMap()
byte._CF_maxInclusive = facets.CF_maxInclusive(value_datatype=byte, super_facet=short._CF_maxInclusive, value=byte(127))
byte._CF_minInclusive = facets.CF_minInclusive(value_datatype=byte, super_facet=short._CF_minInclusive, value=byte(-128))
byte._InitializeFacetMap(byte._CF_maxInclusive,
   byte._CF_minInclusive)
unsignedShort._CF_maxInclusive = facets.CF_maxInclusive(value_datatype=unsignedShort, super_facet=unsignedInt._CF_maxInclusive, value=unsignedShort(65535))
unsignedShort._InitializeFacetMap(unsignedShort._CF_maxInclusive)
unsignedByte._CF_maxInclusive = facets.CF_maxInclusive(value_datatype=unsignedByte, super_facet=unsignedShort._CF_maxInclusive, value=unsignedByte(255))
unsignedByte._InitializeFacetMap(unsignedByte._CF_maxInclusive)
