
import facets
from datatypes import *
string._CF_length = facets.CF_length()
string._CF_enumeration = facets.CF_enumeration(value_datatype=string)
string._CF_whiteSpace = facets.CF_whiteSpace(value=facets._WhiteSpace_enum.WSV_preserve)
string._CF_pattern = facets.CF_pattern()
string._CF_minLength = facets.CF_minLength()
string._CF_maxLength = facets.CF_maxLength()
gMonth._CF_pattern = facets.CF_pattern()
gMonth._CF_enumeration = facets.CF_enumeration(value_datatype=gMonth)
gMonth._CF_whiteSpace = facets.CF_whiteSpace(value=facets._WhiteSpace_enum.WSV_collapse)
gMonth._CF_maxExclusive = facets.CF_maxExclusive(value_datatype=anySimpleType)
gMonth._CF_minInclusive = facets.CF_minInclusive(value_datatype=gMonth)
gMonth._CF_minExclusive = facets.CF_minExclusive(value_datatype=anySimpleType)
gMonth._CF_maxInclusive = facets.CF_maxInclusive(value_datatype=gMonth)
decimal._CF_totalDigits = facets.CF_totalDigits()
decimal._CF_enumeration = facets.CF_enumeration(value_datatype=decimal)
decimal._CF_minExclusive = facets.CF_minExclusive(value_datatype=anySimpleType)
decimal._CF_whiteSpace = facets.CF_whiteSpace(value=facets._WhiteSpace_enum.WSV_collapse)
decimal._CF_maxExclusive = facets.CF_maxExclusive(value_datatype=anySimpleType)
decimal._CF_pattern = facets.CF_pattern()
decimal._CF_minInclusive = facets.CF_minInclusive(value_datatype=decimal)
decimal._CF_fractionDigits = facets.CF_fractionDigits()
decimal._CF_maxInclusive = facets.CF_maxInclusive(value_datatype=decimal)
dateTime._CF_pattern = facets.CF_pattern()
dateTime._CF_enumeration = facets.CF_enumeration(value_datatype=dateTime)
dateTime._CF_whiteSpace = facets.CF_whiteSpace(value=facets._WhiteSpace_enum.WSV_collapse)
dateTime._CF_maxExclusive = facets.CF_maxExclusive(value_datatype=anySimpleType)
dateTime._CF_minInclusive = facets.CF_minInclusive(value_datatype=dateTime)
dateTime._CF_minExclusive = facets.CF_minExclusive(value_datatype=anySimpleType)
dateTime._CF_maxInclusive = facets.CF_maxInclusive(value_datatype=dateTime)
duration._CF_pattern = facets.CF_pattern()
duration._CF_enumeration = facets.CF_enumeration(value_datatype=duration)
duration._CF_whiteSpace = facets.CF_whiteSpace(value=facets._WhiteSpace_enum.WSV_collapse)
duration._CF_maxExclusive = facets.CF_maxExclusive(value_datatype=anySimpleType)
duration._CF_minInclusive = facets.CF_minInclusive(value_datatype=duration)
duration._CF_minExclusive = facets.CF_minExclusive(value_datatype=anySimpleType)
duration._CF_maxInclusive = facets.CF_maxInclusive(value_datatype=duration)
gYear._CF_pattern = facets.CF_pattern()
gYear._CF_enumeration = facets.CF_enumeration(value_datatype=gYear)
gYear._CF_whiteSpace = facets.CF_whiteSpace(value=facets._WhiteSpace_enum.WSV_collapse)
gYear._CF_maxExclusive = facets.CF_maxExclusive(value_datatype=anySimpleType)
gYear._CF_minInclusive = facets.CF_minInclusive(value_datatype=gYear)
gYear._CF_minExclusive = facets.CF_minExclusive(value_datatype=anySimpleType)
gYear._CF_maxInclusive = facets.CF_maxInclusive(value_datatype=gYear)
anyURI._CF_length = facets.CF_length()
anyURI._CF_enumeration = facets.CF_enumeration(value_datatype=anyURI)
anyURI._CF_whiteSpace = facets.CF_whiteSpace(value=facets._WhiteSpace_enum.WSV_collapse)
anyURI._CF_pattern = facets.CF_pattern()
anyURI._CF_minLength = facets.CF_minLength()
anyURI._CF_maxLength = facets.CF_maxLength()
NMTOKENS._CF_length = facets.CF_length()
NMTOKENS._CF_enumeration = facets.CF_enumeration(value_datatype=NMTOKENS)
NMTOKENS._CF_whiteSpace = facets.CF_whiteSpace()
NMTOKENS._CF_pattern = facets.CF_pattern()
NMTOKENS._CF_minLength = facets.CF_minLength(value=nonNegativeInteger(1L))
NMTOKENS._CF_maxLength = facets.CF_maxLength()
gDay._CF_pattern = facets.CF_pattern()
gDay._CF_enumeration = facets.CF_enumeration(value_datatype=gDay)
gDay._CF_whiteSpace = facets.CF_whiteSpace(value=facets._WhiteSpace_enum.WSV_collapse)
gDay._CF_maxExclusive = facets.CF_maxExclusive(value_datatype=anySimpleType)
gDay._CF_minInclusive = facets.CF_minInclusive(value_datatype=gDay)
gDay._CF_minExclusive = facets.CF_minExclusive(value_datatype=anySimpleType)
gDay._CF_maxInclusive = facets.CF_maxInclusive(value_datatype=gDay)
gYearMonth._CF_pattern = facets.CF_pattern()
gYearMonth._CF_enumeration = facets.CF_enumeration(value_datatype=gYearMonth)
gYearMonth._CF_whiteSpace = facets.CF_whiteSpace(value=facets._WhiteSpace_enum.WSV_collapse)
gYearMonth._CF_maxExclusive = facets.CF_maxExclusive(value_datatype=anySimpleType)
gYearMonth._CF_minInclusive = facets.CF_minInclusive(value_datatype=gYearMonth)
gYearMonth._CF_minExclusive = facets.CF_minExclusive(value_datatype=anySimpleType)
gYearMonth._CF_maxInclusive = facets.CF_maxInclusive(value_datatype=gYearMonth)
IDREFS._CF_length = facets.CF_length()
IDREFS._CF_enumeration = facets.CF_enumeration(value_datatype=IDREFS)
IDREFS._CF_whiteSpace = facets.CF_whiteSpace()
IDREFS._CF_pattern = facets.CF_pattern()
IDREFS._CF_minLength = facets.CF_minLength(value=nonNegativeInteger(1L))
IDREFS._CF_maxLength = facets.CF_maxLength()
hexBinary._CF_length = facets.CF_length()
hexBinary._CF_enumeration = facets.CF_enumeration(value_datatype=hexBinary)
hexBinary._CF_whiteSpace = facets.CF_whiteSpace(value=facets._WhiteSpace_enum.WSV_collapse)
hexBinary._CF_pattern = facets.CF_pattern()
hexBinary._CF_minLength = facets.CF_minLength()
hexBinary._CF_maxLength = facets.CF_maxLength()
float._CF_pattern = facets.CF_pattern()
float._CF_enumeration = facets.CF_enumeration(value_datatype=float)
float._CF_whiteSpace = facets.CF_whiteSpace(value=facets._WhiteSpace_enum.WSV_collapse)
float._CF_maxExclusive = facets.CF_maxExclusive(value_datatype=anySimpleType)
float._CF_minInclusive = facets.CF_minInclusive(value_datatype=float)
float._CF_minExclusive = facets.CF_minExclusive(value_datatype=anySimpleType)
float._CF_maxInclusive = facets.CF_maxInclusive(value_datatype=float)
boolean._CF_pattern = facets.CF_pattern()
boolean._CF_whiteSpace = facets.CF_whiteSpace(value=facets._WhiteSpace_enum.WSV_collapse)
base64Binary._CF_length = facets.CF_length()
base64Binary._CF_enumeration = facets.CF_enumeration(value_datatype=base64Binary)
base64Binary._CF_whiteSpace = facets.CF_whiteSpace(value=facets._WhiteSpace_enum.WSV_collapse)
base64Binary._CF_pattern = facets.CF_pattern()
base64Binary._CF_minLength = facets.CF_minLength()
base64Binary._CF_maxLength = facets.CF_maxLength()
gMonthDay._CF_pattern = facets.CF_pattern()
gMonthDay._CF_enumeration = facets.CF_enumeration(value_datatype=gMonthDay)
gMonthDay._CF_whiteSpace = facets.CF_whiteSpace(value=facets._WhiteSpace_enum.WSV_collapse)
gMonthDay._CF_maxExclusive = facets.CF_maxExclusive(value_datatype=anySimpleType)
gMonthDay._CF_minInclusive = facets.CF_minInclusive(value_datatype=gMonthDay)
gMonthDay._CF_minExclusive = facets.CF_minExclusive(value_datatype=anySimpleType)
gMonthDay._CF_maxInclusive = facets.CF_maxInclusive(value_datatype=gMonthDay)
double._CF_pattern = facets.CF_pattern()
double._CF_enumeration = facets.CF_enumeration(value_datatype=double)
double._CF_whiteSpace = facets.CF_whiteSpace(value=facets._WhiteSpace_enum.WSV_collapse)
double._CF_maxExclusive = facets.CF_maxExclusive(value_datatype=anySimpleType)
double._CF_minInclusive = facets.CF_minInclusive(value_datatype=double)
double._CF_minExclusive = facets.CF_minExclusive(value_datatype=anySimpleType)
double._CF_maxInclusive = facets.CF_maxInclusive(value_datatype=double)
QName._CF_length = facets.CF_length()
QName._CF_enumeration = facets.CF_enumeration(value_datatype=QName)
QName._CF_whiteSpace = facets.CF_whiteSpace(value=facets._WhiteSpace_enum.WSV_collapse)
QName._CF_pattern = facets.CF_pattern()
QName._CF_minLength = facets.CF_minLength()
QName._CF_maxLength = facets.CF_maxLength()
normalizedString._CF_whiteSpace = facets.CF_whiteSpace(super_facet=string._CF_whiteSpace, value=facets._WhiteSpace_enum.WSV_replace)
ENTITIES._CF_length = facets.CF_length()
ENTITIES._CF_enumeration = facets.CF_enumeration(value_datatype=ENTITIES)
ENTITIES._CF_whiteSpace = facets.CF_whiteSpace()
ENTITIES._CF_pattern = facets.CF_pattern()
ENTITIES._CF_minLength = facets.CF_minLength(value=nonNegativeInteger(1L))
ENTITIES._CF_maxLength = facets.CF_maxLength()
date._CF_pattern = facets.CF_pattern()
date._CF_enumeration = facets.CF_enumeration(value_datatype=date)
date._CF_whiteSpace = facets.CF_whiteSpace(value=facets._WhiteSpace_enum.WSV_collapse)
date._CF_maxExclusive = facets.CF_maxExclusive(value_datatype=anySimpleType)
date._CF_minInclusive = facets.CF_minInclusive(value_datatype=date)
date._CF_minExclusive = facets.CF_minExclusive(value_datatype=anySimpleType)
date._CF_maxInclusive = facets.CF_maxInclusive(value_datatype=date)
time._CF_pattern = facets.CF_pattern()
time._CF_enumeration = facets.CF_enumeration(value_datatype=time)
time._CF_whiteSpace = facets.CF_whiteSpace(value=facets._WhiteSpace_enum.WSV_collapse)
time._CF_maxExclusive = facets.CF_maxExclusive(value_datatype=anySimpleType)
time._CF_minInclusive = facets.CF_minInclusive(value_datatype=time)
time._CF_minExclusive = facets.CF_minExclusive(value_datatype=anySimpleType)
time._CF_maxInclusive = facets.CF_maxInclusive(value_datatype=time)
NOTATION._CF_length = facets.CF_length()
NOTATION._CF_enumeration = facets.CF_enumeration(value_datatype=NOTATION)
NOTATION._CF_whiteSpace = facets.CF_whiteSpace(value=facets._WhiteSpace_enum.WSV_collapse)
NOTATION._CF_pattern = facets.CF_pattern()
NOTATION._CF_minLength = facets.CF_minLength()
NOTATION._CF_maxLength = facets.CF_maxLength()
integer._CF_pattern = facets.CF_pattern()
integer._CF_fractionDigits = facets.CF_fractionDigits(value=nonNegativeInteger(0L))
token._CF_whiteSpace = facets.CF_whiteSpace(super_facet=normalizedString._CF_whiteSpace, value=facets._WhiteSpace_enum.WSV_collapse)
nonNegativeInteger._CF_minInclusive = facets.CF_minInclusive(value_datatype=nonNegativeInteger, value=nonNegativeInteger(0L))
long._CF_minInclusive = facets.CF_minInclusive(value_datatype=long, value=long(-9223372036854775808L))
long._CF_maxInclusive = facets.CF_maxInclusive(value_datatype=long, value=long(9223372036854775807L))
language._CF_pattern = facets.CF_pattern()
int._CF_minInclusive = facets.CF_minInclusive(value_datatype=int, super_facet=long._CF_minInclusive, value=int(-2147483648))
int._CF_maxInclusive = facets.CF_maxInclusive(value_datatype=int, super_facet=long._CF_maxInclusive, value=int(2147483647))
Name._CF_pattern = facets.CF_pattern()
short._CF_minInclusive = facets.CF_minInclusive(value_datatype=short, super_facet=int._CF_minInclusive, value=short(-32768))
short._CF_maxInclusive = facets.CF_maxInclusive(value_datatype=short, super_facet=int._CF_maxInclusive, value=short(32767))
nonPositiveInteger._CF_maxInclusive = facets.CF_maxInclusive(value_datatype=nonPositiveInteger, value=nonPositiveInteger(0L))
negativeInteger._CF_maxInclusive = facets.CF_maxInclusive(value_datatype=negativeInteger, super_facet=nonPositiveInteger._CF_maxInclusive, value=negativeInteger(-1L))
positiveInteger._CF_minInclusive = facets.CF_minInclusive(value_datatype=positiveInteger, super_facet=nonNegativeInteger._CF_minInclusive, value=positiveInteger(1L))
NMTOKEN._CF_pattern = facets.CF_pattern()
unsignedLong._CF_maxInclusive = facets.CF_maxInclusive(value_datatype=unsignedLong, value=unsignedLong(18446744073709551615L))
byte._CF_minInclusive = facets.CF_minInclusive(value_datatype=byte, super_facet=short._CF_minInclusive, value=byte(-128))
byte._CF_maxInclusive = facets.CF_maxInclusive(value_datatype=byte, super_facet=short._CF_maxInclusive, value=byte(127))
NCName._CF_pattern = facets.CF_pattern(super_facet=Name._CF_pattern)
unsignedInt._CF_maxInclusive = facets.CF_maxInclusive(value_datatype=unsignedInt, super_facet=unsignedLong._CF_maxInclusive, value=unsignedInt(4294967295L))
unsignedShort._CF_maxInclusive = facets.CF_maxInclusive(value_datatype=unsignedShort, super_facet=unsignedInt._CF_maxInclusive, value=unsignedShort(65535L))
unsignedByte._CF_maxInclusive = facets.CF_maxInclusive(value_datatype=unsignedByte, super_facet=unsignedShort._CF_maxInclusive, value=unsignedByte(255L))
