#!/usr/bin/env python

import pyxb.namespace
import sys
import traceback

#pyxb.namespace.NamespaceArchives('/dev/null', reset=True)
for fn in sys.argv[1:]:
    nsa = pyxb.namespace.NamespaceArchive(archive_path=fn)
    print 'File %s archives %d namespaces:' % (fn, len(nsa.namespaces()))
    for ns in nsa.namespaces().copy():
        print ' namespace=%s' % (ns,)
        ns.validateComponentModel()
        print ' module-path=%s' % (ns.modulePath(),)
        for cat in ns.categories():
            cat_map = ns.categoryMap(cat)
            for (k, v) in cat_map.items():
                print '  %s %s: %s' % (cat, ns.createExpandedName(k), v)

# LocalVariables:
# mode:python
# End:

