#!/usr/bin/env python

import pyxb.namespace
import sys
import traceback

for fn in sys.argv[1:]:
    nsa = pyxb.namespace.NamespaceArchive(archive_path=fn)
    print 'File %s archives %d namespaces:' % (fn, len(nsa.namespaces()))
    for ns in nsa.namespaces().copy():
        print ' namespace=%s' % (ns,)
        ns.validateComponentModel()
        print ' module-path=%s' % (ns.modulePath(),)
        for td in ns.typeDefinitions().values():
            print '  td %s' % (td.expandedName(),)

# LocalVariables:
# mode:python
# End:

