#!/usr/bin/env python

import pyxb.namespace
import sys
import traceback
import pyxb.xmlschema.structures

pyxb.namespace.archive.NamespaceArchive.PreLoadArchives()
for fn in sys.argv[1:]:
    nsa = None
    try:
        nsa = pyxb.namespace.archive.NamespaceArchive.ForPath(fn)
    except pyxb.NamespaceArchiveError, e:
        print '%s: %s' % (fn, e)
        continue
    print '%s : %d namespaces:' % (fn, len(nsa.namespaces()))
    nsa.readNamespaces()
    for mr in nsa.moduleRecords():
        print ' %s : %s, module-path=%s' % (mr.namespace(), mr.generationUID(), mr.modulePath())
        for origin in mr.origins():
            print '  + %s' % (origin,)
            for (c, k) in origin.categoryMembers().iteritems():
                print '   - %s %d items' % (c, len(k))

# LocalVariables:
# mode:python
# End:

