"""pywxsb.binding -- Material used in bindings generated by the PyWXSB package.
"""

# Automatically include all the stuff that's necessary for basic
# running.  There are order dependencies here.
import basis
import datatypes
import facets
import datatypes_facets
import content

# Do not include the stuff that's required only for code generation
# noimport nfa
# noimport generate
